---
- hosts: 127.0.0.1
  collections: ['debops.debops', 'debops.roles01', 'debops.roles02', 'debops.roles03']
  roles:
    - role: ansible-role-certbot
      debug:
        msg: "certbot_domains is {{ certbot_domains }}"
      vars:
        certbot_auto_renew_user: "{{ override_certbot_auto_renew_user | default('devin') }}"
        certbot_admin_email: "{{ override_certbot_admin_email | default('devin@callysto.com') }}"
        certbot_certs:
          - domains: "{{ certbot_domains | default([lookup('file', '/etc/hostname')]) }}"
        certbot_repo: https://github.com/certbot/certbot.git
        certbot_version: master
        certbot_keep_updated: true
        certbot_auto_renew_minute: 19
        certbot_auto_renew_hour: 03
        certbot_create_if_missing: yes
        # don't assume we have nginx; override default to empty
        certbot_create_standalone_stop_services: []
    - role: debops.roles01.postfix
    - role: debops.roles02.postwhite
    - role: debops.roles03.postscreen
