---
- hosts: 127.0.0.1
  gather_facts: true
  collections: ['ansible.posix', 'community.general']
  roles:
    - role: kyl191.openvpn
      inventory_hostname: "{{ inventory_hostname }}"
      openvpn_server_ipv6_network: "{{ openvpn_server_ipv6_network }}"
      clients:
        - medusa
        - devin-laptop
        - devin-phone
        - alana-laptop
        - alana-phone
        - client1
        - client2
        - client3
        - client4
        - client5
