---
- hosts: 127.0.0.1
  collections: [ 'debops.debops', 'debops.roles01', 'debops.roles02', 'debops.roles03' ]
  roles:
    - debops.debops.etckeeper
    - debops.debops.netbase
    - debops.roles03.fail2ban
    - debops.debops.sshd
