---
- hosts: 127.0.0.1
  collections: ['debops.debops', 'debops.roles01', 'debops.roles02', 'debops.roles03']
  roles:
    - role: debops.debops.apt_install
      vars:
        apt_install__packages:
          - certbot # TODO replace
    - role: debops.roles01.postfix
    - role: debops.roles02.postwhite
    - role: debops.roles03.postscreen
